[package]
name = "lightswitch"
version = "0.1.0"
authors = ["Josh Marron <marronjosh@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille="3.0.0"
maplit="1.0.2"
